export const wordStyles = {
  intentional: {
    word: 'intentional',
    fontFamily: "'Helvetica Neue', sans-serif",
    color: '#241013',
    fontWeight: 400,
    letterSpacing: '-0.02em',
    fontStyle: 'italic' as const,
    decoration: 'none' as const,
    decorationColor: undefined,
    gradient: 'linear-gradient(135deg, #241013, #5C3A2E, #241013)',
    baselineOffset: undefined,
    showHandDrawn: false,
    showBadge: false,
    showArrow: false,
    buttonStyle: { bg: '#FF3C1A', text: '#FAF7EF', border: 'none', radius: '100px', shadow: 'none', fontFamily: "'Helvetica Neue', sans-serif", fontWeight: 400 },
    contactStyle: { fontFamily: "'Helvetica Neue', sans-serif", color: '#241013', fontWeight: 400, fontStyle: 'normal' as const, letterSpacing: '-0.08rem' },
    letsTalkText: "Let\u2019s talk.",
  },
  human: {
    word: 'human',
    fontFamily: "var(--font-cooper-black), 'Cooper Black', 'Cooper Std', serif",
    color: '#A73F27',
    fontWeight: 900,
    letterSpacing: '-0.02em',
    fontStyle: 'italic' as const,
    decoration: 'none' as const,
    decorationColor: undefined,
    gradient: undefined,
    baselineOffset: undefined,
    showHandDrawn: true,
    showBadge: false,
    showArrow: false,
    buttonStyle: { bg: '#A73F27', text: '#FAF7EF', border: 'none', radius: '100px', shadow: 'none', fontFamily: "'Helvetica Neue', sans-serif", fontWeight: 700 },
    contactStyle: { fontFamily: "var(--font-cooper-black), 'Cooper Black', serif", color: '#A73F27', fontWeight: 900, fontStyle: 'italic' as const, letterSpacing: '-0.08rem' },
    letsTalkText: "Let\u2019s talk!",
  },
  trustworthy: {
    word: 'trustworthy',
    fontFamily: "'Helvetica Neue', sans-serif",
    color: '#2927A7',
    fontWeight: 400,
    letterSpacing: '-0.02em',
    fontStyle: 'normal' as const,
    decoration: 'none' as const,
    decorationColor: undefined,
    gradient: undefined,
    baselineOffset: undefined,
    showHandDrawn: false,
    showBadge: true,
    showArrow: false,
    buttonStyle: { bg: 'transparent', text: '#2927A7', border: '2px solid #2927A7', radius: '4px', shadow: 'none', fontFamily: "'Helvetica Neue', sans-serif", fontWeight: 500 },
    contactStyle: { fontFamily: "'Helvetica Neue', sans-serif", color: '#2927A7', fontWeight: 400, fontStyle: 'normal' as const, letterSpacing: '-0.08rem' },
    letsTalkText: "Let\u2019s talk.",
  },
  unique: {
    word: 'unique',
    fontFamily: "'Century Gothic', 'Futura', sans-serif",
    color: '#8F27A7',
    fontWeight: 500,
    baselineOffset: '-0.04em',
    letterSpacing: '-0.05em',
    fontStyle: 'normal' as const,
    decoration: 'none' as const,
    decorationColor: undefined,
    gradient: undefined,
    showHandDrawn: false,
    showBadge: false,
    showArrow: true,
    buttonStyle: { bg: '#F0F427', text: '#000000', border: '2px solid black', radius: '9999px', shadow: '2px 4px 0px 0px black', fontFamily: "'Century Gothic', sans-serif", fontWeight: 500 },
    contactStyle: { fontFamily: "'Century Gothic', 'Futura', sans-serif", color: '#8F27A7', fontWeight: 500, fontStyle: 'normal' as const, letterSpacing: '-0.05em' },
    letsTalkText: "Let\u2019s talk.",
  },
} as const;

export type WordKey = keyof typeof wordStyles;
export const wordOrder: WordKey[] = ['intentional', 'human', 'trustworthy', 'unique'];
